### ISSUE TITLE
Possible Wrong Total Txs for Address

### ISSUE THREAD

**Issue by olgakup** [EthVM/ethvm#333]
* **I'm submitting a ...**
    - [x] bug report

* **Bug Report**
    for address:  
http://ethvm.lan/address/0x88d74a59454f6cf3b51ef6b9136afb6b9d405a88

we are getting a total of 1,245 txs, while on etherscan that address has a total of 8 txs.
https://etherscan.io/address/0x88d74a59454f6cf3b51ef6b9136afb6b9d405a88

**Comment by aldoborrero** [comment]
@olgakup I'll leave this issue for now as @brianmcgee is improving our Mongo sink connector. Once that task is finished I'll generate a new dataset and we can double check again :)

**Comment by aldoborrero** [comment]
<img width="909" alt="screen shot 2019-02-13 at 12 55 20" src="https://user-images.githubusercontent.com/82811/52710059-aadd4480-2f8e-11e9-8e2f-cb2b70160741.png">

**Comment by brianmcgee** [comment]
When processing transactions we generate a `TokenTransfer` for the transaction itself and an additional `TokenTransfer` which represents the movement of ether to the miner (tx fee). We are not currently distinguishing these fee transfers separately from the original transfer and that's why the number is incorrect. I'll have a look at correct this in the next day or two by distinguishing between these two transfer types.
