### ISSUE TITLE
How to connect my local etherum data by explorer

### ISSUE THREAD

**Issue by tei-bizblocks** [EthVM/ethvm#338]
This is great works!

I need explorer for my private etherum blockchain network.

How to collect blockchain data and show on explorer? 

plz. I need help

**Comment by aldoborrero** [comment]
Hi @tei-bizblocks,

looks like you want to "read" the data from your explorer and feed it trough the web interface, right?

This project needs a customized version of Ethereum (in our case EthereumJ) and process that information trough Apache Kafka. So there's no way of "reading" an already synced node to the explorer.

I recommend you to take a look on the [Wiki](https://github.com/EthVM/ethvm/wiki) so you can setup your machine to be ready to execute the project. Depending on how much data you want to process it may take you time to do it properly.

Also keep in mind we are finishing well known bugs on the process (so the data displayed could not be accurate).

**Comment by tei-bizblocks** [comment]
I run  ./bin/ethvm.sh docker up
all container is ok. But sync is not complete.
I can see Explorer page, Maybe  this is not realtime sync.
Maybe use ‘datasets/mainnet_sample.mongo.archive’.
How run realtime sync?

**Comment by aldoborrero** [comment]
Hey @tei-bizblocks in order to start processing blocks:

1. You have to start EthereumKafkaStarter that you can find on apps/ethereumj (make sure you have checked out properly the submodule as the Wiki instructions says)

<img width="979" alt="screen shot 2019-02-13 at 21 41 27" src="https://user-images.githubusercontent.com/82811/52742519-30391700-2fd8-11e9-9e6d-be03f81ab8da.png">

2. Make sure that before running EthereumKafkaStarter, the other components are ready, specially Kafka, Kafka-Connect and Zookeeper.

3. The explorer will disable realtime notifications while syncing, but you can query the data. I recommend you to run only EthereumJ until certain block. This process is very intensive so your laptop may degrade in performance.

**Comment by tei-bizblocks** [comment]
I am deeply grateful for your help.
I learned a lot thanks to that.
I hope that ethvm will replace etherscan as soon as possible.
Thanks!

**Comment by aldoborrero** [comment]
Hey @tei-bizblocks I've updated the Wiki page with more information on [how to setup properly the environment](https://github.com/EthVM/ethvm/wiki/Running-EthVM)! Take a look!

**Comment by ashishxooa** [comment]
@aldoborrero I am not a java developer, so couldn't understand the instructions. Can you please help with some commands for people like me to get started. My EthVM stack is running and I can see the UI but it has no data. I started the parity node with Ropsten n/w. Even I would like to have my own private n/w's data in EthVM.
