### ISSUE TITLE
Token Details Enhancements - Frontend

### ISSUE THREAD

**Issue by gsiuniak** [EthVM/EthVM#366]
**NOTE:**
This issue is cross-referenced in #364 

**Token Details:**
  - [x] Owner/Total Holders missing on all tokens. Currently displays "REQUIRED DATA"
  See: http://ethvm.lan/token/0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48

  - [x] If data is missing, for example "support" detail, the details for that row are blank. Should either be populated, or the row not displayed.
  See: http://ethvm.lan/token/0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48

  - [x] Pagination is using vuetify, not AppPagination. Does not dynamically fetch more data on table-page change for both transactions and holders.
  See: http://ethvm.lan/token/0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48

  - [x] Not all of the calls are from internal APIs. This causes some data to be mismatched (aka we are missing data for particular addresses obtained from ethsplorer). Still getting information from ethsplorer from:
    - fetchTokenTransfers
    - fetchTokenHolders
    - fetchHolderDetails
    - fetchHolderTransfers

  - [x] Values are not formatted to be human-readable.
  See: http://ethvm.lan/token/0x05f4a42e251f2d52b8ed15e9fedaacfcef1fad27?holder=0xde5a57b9ba909c332cb7be7133ec29e228fb0286

**Comment by aldoborrero** [comment]
Several comments:

- Owner/Total Holders missing on all tokens. Currently displays "REQUIRED DATA"
  - We don't have on the processing engine time to add on Milestone 1 Owner or Total Holders. This also was mentioned and moved to Milestone 2. So I suggest to hide those fields.

- If data is missing, for example "support" detail, the details for that row are blank. Should either be populated, or the row not displayed.
  - Those details are gathered from this [repository](https://github.com/MyEtherWallet/ethereum-lists/). So that information may be available or not depending on the token. I suggest hiding it.

- Pagination is using vuetify, not AppPagination. Does not dynamically fetch more data on table-page change for both transactions and holders.
  - It should be using AppPagination. As @olgakup is working on implementing the design on #362 make sure that is correctly implemented. API has already pagination for those calls 

- Not all of the calls are from internal APIs. This causes some data to be mismatched (aka we are missing data for particular addresses obtained from ethsplorer). Still getting information from ethsplorer from.
  - This relates to #333 and #360 (@kvhnuke created the S3 bucket) so I can upload properly a bigger dataset. So some of those calls are going to be solved with that, others needs to be moved to M2 as I was writing before.

- Values are not formatted to be human-readable.
  - We have models for Eth, Address, Hex. Just use those classes our create custom ones for those values that needs to be in human readable form.

Please @gsiuniak and @olgakup coordinate between yourselves to avoid having merge issues and conflicts. I assign this task to @olgakup as she's working on implementing the design on #362

**Comment by olgakup** [comment]
@aldoborrero let me know of the calls are there yet.
