### ISSUE TITLE
Bug - Uncles / Pagination

### ISSUE THREAD

**Issue by gsiuniak** [EthVM/ethvm#376]
**NOTE:**
This issue is cross-referenced in #364 
Although #336 is mentioned below, I'm not sure it is related.

**Uncles / Pagination**

* [x]  Last page of results in incorrect. Possibly incorrect display on pagination. Click "last" to replicate
  See: http://ethvm.lan/uncles
  NOTE: Last pagination seems to work on http://ethvm.lan/blocks
  Issue: #336
  Assigned to: @gsiuniak

**Comment by aldoborrero** [comment]
Hey @gsiuniak you are right about:

> /**
     * Total number of Uncles is not necessarily equal the highest block number of uncles in the DB.
     * E.G. getTotalNumberOfUncles returns 10879, but the number of the first entry I see
     * in the DB is number: 105019 blockNumber: 105021. Highest is 127405.
     */

The only problem I see is that we are using .skip(), so as the Mongo Docs states:

> The cursor.skip() method requires the server to scan from the beginning of the input results set before beginning to return results. As the offset increases, cursor.skip() will become slower.

So I assume with the current data-set we are not seeing that, initially I was using it but that's why I changed it to avoid the skip call and started using ranged queries (https://docs.mongodb.com/manual/reference/method/cursor.skip/#using-range-queries)

**Comment by aldoborrero** [comment]
Having said that, what I've done for now until we do it properly on processing, is to leave your version of the code. On the front-end is disabled free input.
